
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: default
data:
  # example of a simple property defined using --from-literal
  example.property.1: hello1
  example.property.2: world1

