# overlay.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  # override replicas
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          # override resources
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
