apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-many-cont1
  labels:
    app: op-many-cont1
spec:
  replicas: 1
  template:
    metadata:
      name: op-many-cont1
      labels:
        app: op-many-cont1
    spec:
      containers:
        - name: opcont1
          image: opavlova/db-mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3307
        - name: opcont2
          image: tomcat
          ports:
            - containerPort: 8081
      restartPolicy: Always
  selector:
    matchLabels:
      app: op-many-cont1
#  kubectl apply -f deployment_op-many-cont.yaml
