
apiVersion: v1
kind: Pod
metadata:
  name: equalinpods2
spec:
  containers:
    - name: equalinpods2
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY1
          valueFrom:
            configMapKeyRef:
              name: equalinpods
              key: equalinpods.test.java
