kind: 'CustomResourceDefinition'
apiVersion: 'apiextensions.k8s.io/v1beta1'
metadata:
  name: metrics.config.istio.io
  labels:     
    package: metric
    istio: mixer-instance
spec:
  group: config.istio.io
  names:
    kind: metric
    plural: metrics
    singular: metric
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10

