
apiVersion: v1
kind: Pod
metadata:
  name: equaljavakeys
spec:
  containers:
    - name: equaljavakeys
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY1
          valueFrom:
            configMapKeyRef:
              name: equaljavakeys
              key: equaljavakeys.test.java
