apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: default
data:
  game.properties: |
    secret.code.lives=30
    secret.code.allowed=true
  ui.properties: |
    color.good=purple
    color.bad =yellow


