apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment_label_selectors
  labels:
    app: test_value
spec:
  replicas: 1
  template:
    metadata:
      name: Deployment_label_selectors
      labels:
        app: test_value
  selector:
    matchLabels:
      app: etcd