apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: example-config-op
  namespace: default
data:
  test.json: |-
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "metadata": {
        "deletionGracePeriodSeconds": 44,
        "name": "rbd2",
        "resourceVersion": "22",
        "creationTimestamp": "ss"
      },
      "spec": {
        "containers": [
          {
            "name": "rbd-rw",
            "image": "kubernetes/pause",

            "volumeMounts": [
              {
                "mountPath": "/mnt/rbd",
                "name": "rbdpd",
                "mountPropagation": "",
                "subPath": "",
                "readOnly": false
              }
            ]
          }
        ],
        "nodeSelector": {
          "test_comp": "testing_c"
        },
        "volumes": [
          {
            "name": "rbdpd",
            "rbd": {
              "keyring": "",
              "monitors": [
                "10.16.154.78:6789"
              ],
              "pool": "kube",
              "image": "foo",
              "user": "admin",
              "secretRef": {
                "name": "ceph-secret"
              },
              "fsType": "ext4",
              "readOnly": true,

            }
          }
        ]
      }
    }

