apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: example-config-op
  namespace: default
data:
  test.javascript: |-
    fetch("jaxrs_employee/")
    function connect() {
        var url = 'ws://localhost'
        var socket_ws = new WebSocket(url);
        stompClient1 = Stomp.over(socket_ws);

        stompClient1.connect({}, function (frame) {
            setConnected(true);
            console.log('Connected: ' + frame);
            stompClient1.subscribe('/topic/greetings', function (greeting) {
                showGreeting(JSON.parse(greeting.body).content);
            });
    });

