apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: example-config-op
  namespace: default
data:
  test.hql.query: |-
    from Entitybus
  test.query: |-
    SELECT a FROM ENTITYBUS a
