apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: example-config-op
  namespace: default
data:
  test.yaml: v1
  test1.test2.yaml: test
  test1:
    test3:



