---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: widgets.example.com
spec:
  group: example.com
  names:
    kind: Widget
    plural: widgets
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        spec:
          properties:
            somestring:
              type: string
          required:
            - somestring
          type: object
        status1:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: cogs.example.com
spec:
  group: example.com
  names:
    kind: Cog
    plural: cogs
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        spec:
          properties:
            somestring:
              type: string
          required:
            - somestring
          type: object
        status1:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
        status5:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: metrics.config.istio.io
  labels:
    package: metric
    istio: mixer-instance
spec:
  group: config.istio.io
  names:
    kind: metric
    plural: metrics
    singular: metric
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas1:
              type: integer
              minimum: 1
              maximum: 10
---
