apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentlivetemplates
  labels:
    app: deplabel
spec:
  replicas: 1
  template:
    metadata:
      name: deploymentlivetemplates
      labels:
        app: deplabel
    spec:
      containers:
      - name: depname
        image: tomcat
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: deplabel
