apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_name
spec:
  selector:
    matchLabels:
      k8s-app_renamed: cassandra
  template:
    metadata:
      labels:
        k8s-app_renamed: cassandra
        app:
    spec:
      containers:
      - name: test_name
  replicas: 1

