apiVersion: apps/v1
kind: Deployment
metadata:
  name: opmysql-deploy-apply
  labels:
    app: opmysql-deploy-apply
spec:
  replicas: 1
  template:
    metadata:
      name: opmysql-deploy-apply
      labels:
        app: opmysql-deploy-apply
    spec:
      containers:
        - name: opmysql-deploy-apply
          image: opavlova/db-mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
      restartPolicy: Always
  selector:
    matchLabels:
      app: opmysql-deploy-apply

