apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot2
spec:
  selector:
    matchLabels:
      app: gs-spring-boot2
  template:
    metadata:
      labels:
        app: gs-spring-boot2
    spec:
      containers:
        - name: gs-spring-boot2
          image: docker.io/opavlova/gs-spring-boot:latest
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: gs-spring-boot2
spec:
  selector:
    app: gs-spring-boot2
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer