apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment_label_selectors
  labels:
    app: dep_label
spec:
  replicas: 1
  template:
    metadata:
      name: Deployment_label_selectors
      labels:
        app: dep_label
    spec:
      containers:
      - name: dep_name
        image: tomcat
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: dep_label
