apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretclaims.cryptopussecretcontroller.puzzle.ch
spec:
  group: cryptopussecretcontroller.puzzle.ch
  names:
    kind: SecretClaim
    plural: secretclaims
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        spec:
          properties:
            somestring:
              type: string
          required:
            - somestring
          type: object
        status1:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
