apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: widgets.example.com
spec:
  group: example.com
  names:
    kind: Widget
    plural: widgets
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
          required:
            - name
        spec:
          properties:
            somestring:
              type: string
          required:
            - somestring
          type: object
        status1:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
        status2:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
        status3:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
        status4:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object
        status5:
          properties:
            somebool:
              type: boolean
          required:
            - somebool
          type: object