apiVersion: v1
kind: Pod
metadata:
  name: opmysql
#  namespace: op
  labels:
    app: opmysql
spec:
  containers:
    - name: opmysql
      image: "sha256:c6bf9129e93fa374456cf7d6a8dd013e1682d234fd7dffa9816d6949ab27dcee"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
  restartPolicy: Always
