
apiVersion: v1
kind: Pod
metadata:
  name: testmany1
spec:
  containers:
    - name: testmany1
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY1
          valueFrom:
            configMapKeyRef:
              name: renamekeys
              key: rename.example.property.1
        - name: SPECIAL_LEVEL_KEY2
          valueFrom:
            configMapKeyRef:
              name: renamekeys
              key: rename.example.property.1
        - name: SPECIAL_LEVEL_KEY3
          valueFrom:
            configMapKeyRef:
              name: renamekeys
              key: rename.example.property.2